fixed #48
dengaku-club/anitize.js pull request #70
Opened 2017-08-11 18:05 UTC by dadaa

2017-08-12 00:26 UTC, shundroid requested changes

2017-08-12 00:26 UTC, shundroid commented on src/reducers/submit.js
> +}
ここ、 reducers/player.js と分けているのはどうしてでしょうか。
そっちのほうでデータを持っているので、それを使えばいい気がします。

2017-08-12 00:26 UTC, shundroid commented on src/utils/submit.js
> +    alert('sucess!');
あ、c が１つない！

2017-08-12 00:27 UTC, shundroid commented
@dadaa あと、eslint でエラーが出ているので、 `npm run lint:fix` で直してください。
ちょっとこれから学校見学なので、続きは午後です・・

2017-08-12 07:17 UTC, dadaa commented on src/reducers/submit.js
> +}
たしかにー

2017-08-12 07:17 UTC, dadaa commented on src/utils/submit.js
> +    alert('sucess!');
たしかにー

2017-08-12 08:02 UTC, shundroid requested changes

2017-08-12 08:02 UTC, shundroid commented on src/components/palette/SubmitButton.js
> +    submit(this.props.joinedImage, this.props.duration);
`@utils/submit` が middleware になっていて、
onClick 時に SUBMIT みたいなアクションが作られて、
それを submit 側で監視して、動きはじめるみたいにするのはどうでしょうか。

http://redux.js.org/docs/advanced/Middleware.html

store への登録は `stores/index.js` に applyMiddleware してくださいませ

2017-08-12 08:02 UTC, shundroid commented on src/utils/submit.js
> +export default function submit(joinedImage, duration) {
そうすると引数で渡さなくても joinedImage と duration が store から取れますね

2017-08-12 15:31 UTC, dadaa commented on src/components/palette/SubmitButton.js
> +    submit(this.props.joinedImage, this.props.duration);
なんか middleware は、reducer に来るまでのイベントを横取りして、なんだか処理して、またイベントを流すようなイメージかと思ったので、ここでイベントを消費しちゃうのもなんだかおかしいかしら？と思ったのよね。
で、似たようなところ、つまりComponent に影響を与えない機能はどうやって実装しているのかな？を debugger.html 内にあるか調べてみたの。で、例えば clipboard に値をセットするところなどがあって、そういうところはイベントを出さずに直接呼んでるので、同じようにしてみたんです。
https://github.com/devtools-html/debugger.html/blob/0ab605e797178aac92e9fd5480b63844ca4be15b/src/components/Editor/EditorMenu.js#L34
どうかしらね？

2017-08-13 01:40 UTC, shundroid commented on src/components/palette/SubmitButton.js
> +    submit(this.props.joinedImage, this.props.duration);
なるほどなるほど、たしかにそうですね。
似たようなやつで、Vuex だと、middleware の代わりに、plugin という機能があって、
それはアクションとステートを受け取って、自由にいろいろなことができる機能なので、それの Redux 版なのかと思っていましたけど、ちょっと役割が異なるんですね。

それだと、このままがいいと思います。

2017-08-13 01:41 UTC, shundroid approved these changes

2017-08-13 01:41 UTC, merged