Fixed UI
dengaku-club/anitize.js pull request #85
Opened 2017-08-16 08:31 UTC by shundroid

![18](https://user-images.githubusercontent.com/8530218/29354484-ab4ed8e6-82a8-11e7-9bd9-c27020e788b8.png)

fixed #78 

Please call it "Photon".

2017-08-17 15:39 UTC, dadaa reviewed
かっこいい！！

2017-08-17 15:39 UTC, dadaa commented on src/components/Player.js
> +    window.timing = this.animation.effect.getComputedTiming().progress;
window に持たせるようにした理由はなんです？？？

2017-08-18 01:39 UTC, shundroid commented on src/components/Player.js
> +    window.timing = this.animation.effect.getComputedTiming().progress;
もともとは、Player の子 element として、CurrentTiming を持っていたので、prop で timing を渡せたのですが、
それだと位置を window 基準で指定しなくてはならず、今回のUI の変更で、それだとつらくなったので、
入れ子の関係がなくなっちゃったからです。

redux で action で渡すというのもありかと思いましたが、1秒間に最大60回 UPDATE_TIMING が発生するのもちょっとなので、仕方なく window に持たせました。

2017-08-18 13:00 UTC, dadaa requested changes
なにかコンフリクトがおきているので、それを直したらマージしちゃってください！

2017-08-19 01:08 UTC, merged